/*
Okta Admin Management

Testing DeviceApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package okta

import (
	"context"
	"testing"

	openapiclient "./openapi"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_okta_DeviceApiService(t *testing.T) {
	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DeviceApiService ActivateDevice", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var deviceId string

		resp, httpRes, err := apiClient.DeviceApi.ActivateDevice(context.Background(), deviceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test DeviceApiService DeactivateDevice", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var deviceId string

		resp, httpRes, err := apiClient.DeviceApi.DeactivateDevice(context.Background(), deviceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test DeviceApiService DeleteDevice", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var deviceId string

		resp, httpRes, err := apiClient.DeviceApi.DeleteDevice(context.Background(), deviceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test DeviceApiService GetDevice", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var deviceId string

		resp, httpRes, err := apiClient.DeviceApi.GetDevice(context.Background(), deviceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test DeviceApiService ListDevices", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DeviceApi.ListDevices(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test DeviceApiService SuspendDevice", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var deviceId string

		resp, httpRes, err := apiClient.DeviceApi.SuspendDevice(context.Background(), deviceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test DeviceApiService UnsuspendDevice", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var deviceId string

		resp, httpRes, err := apiClient.DeviceApi.UnsuspendDevice(context.Background(), deviceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})
}
