/*
Okta Admin Management

Testing EmailDomainApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package okta

import (
	"context"
	"testing"

	openapiclient "./openapi"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_okta_EmailDomainApiService(t *testing.T) {
	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test EmailDomainApiService CreateEmailDomain", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.EmailDomainApi.CreateEmailDomain(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test EmailDomainApiService DeleteEmailDomain", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var emailDomainId string

		resp, httpRes, err := apiClient.EmailDomainApi.DeleteEmailDomain(context.Background(), emailDomainId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test EmailDomainApiService GetEmailDomain", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var emailDomainId string

		resp, httpRes, err := apiClient.EmailDomainApi.GetEmailDomain(context.Background(), emailDomainId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test EmailDomainApiService ListEmailDomainBrands", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var emailDomainId string

		resp, httpRes, err := apiClient.EmailDomainApi.ListEmailDomainBrands(context.Background(), emailDomainId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test EmailDomainApiService ListEmailDomains", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.EmailDomainApi.ListEmailDomains(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test EmailDomainApiService ReplaceEmailDomain", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var emailDomainId string

		resp, httpRes, err := apiClient.EmailDomainApi.ReplaceEmailDomain(context.Background(), emailDomainId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test EmailDomainApiService VerifyEmailDomain", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var emailDomainId string

		resp, httpRes, err := apiClient.EmailDomainApi.VerifyEmailDomain(context.Background(), emailDomainId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})
}
