/*
Okta Admin Management

Testing ProfileMappingApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package okta

import (
	"context"
	"testing"

	openapiclient "./openapi"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_okta_ProfileMappingApiService(t *testing.T) {
	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ProfileMappingApiService GetProfileMapping", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var mappingId string

		resp, httpRes, err := apiClient.ProfileMappingApi.GetProfileMapping(context.Background(), mappingId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test ProfileMappingApiService ListProfileMappings", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.ProfileMappingApi.ListProfileMappings(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test ProfileMappingApiService UpdateProfileMapping", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var mappingId string

		resp, httpRes, err := apiClient.ProfileMappingApi.UpdateProfileMapping(context.Background(), mappingId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})
}
