/*
Okta Admin Management

Testing LogStreamApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package okta

import (
	"context"
	"testing"

	openapiclient "./openapi"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_okta_LogStreamApiService(t *testing.T) {
	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test LogStreamApiService ActivateLogStream", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var logStreamId string

		resp, httpRes, err := apiClient.LogStreamApi.ActivateLogStream(context.Background(), logStreamId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test LogStreamApiService CreateLogStream", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.LogStreamApi.CreateLogStream(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test LogStreamApiService DeactivateLogStream", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var logStreamId string

		resp, httpRes, err := apiClient.LogStreamApi.DeactivateLogStream(context.Background(), logStreamId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test LogStreamApiService DeleteLogStream", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var logStreamId string

		resp, httpRes, err := apiClient.LogStreamApi.DeleteLogStream(context.Background(), logStreamId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test LogStreamApiService GetLogStream", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var logStreamId string

		resp, httpRes, err := apiClient.LogStreamApi.GetLogStream(context.Background(), logStreamId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test LogStreamApiService ListLogStreams", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.LogStreamApi.ListLogStreams(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test LogStreamApiService ReplaceLogStream", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var logStreamId string

		resp, httpRes, err := apiClient.LogStreamApi.ReplaceLogStream(context.Background(), logStreamId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})
}
