/*
Okta Admin Management

Testing RiskProviderApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package okta

import (
	"context"
	"testing"

	openapiclient "./openapi"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_okta_RiskProviderApiService(t *testing.T) {
	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RiskProviderApiService CreateRiskProvider", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RiskProviderApi.CreateRiskProvider(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test RiskProviderApiService DeleteRiskProvider", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var riskProviderId string

		resp, httpRes, err := apiClient.RiskProviderApi.DeleteRiskProvider(context.Background(), riskProviderId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test RiskProviderApiService GetRiskProvider", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var riskProviderId string

		resp, httpRes, err := apiClient.RiskProviderApi.GetRiskProvider(context.Background(), riskProviderId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test RiskProviderApiService ListRiskProviders", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RiskProviderApi.ListRiskProviders(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test RiskProviderApiService ReplaceRiskProvider", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var riskProviderId string

		resp, httpRes, err := apiClient.RiskProviderApi.ReplaceRiskProvider(context.Background(), riskProviderId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})
}
