/*
Okta Admin Management

Testing PushProviderApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package okta

import (
	"context"
	"testing"

	openapiclient "./openapi"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_okta_PushProviderApiService(t *testing.T) {
	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PushProviderApiService CreatePushProvider", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.PushProviderApi.CreatePushProvider(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test PushProviderApiService DeletePushProvider", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var pushProviderId string

		resp, httpRes, err := apiClient.PushProviderApi.DeletePushProvider(context.Background(), pushProviderId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test PushProviderApiService GetPushProvider", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var pushProviderId string

		resp, httpRes, err := apiClient.PushProviderApi.GetPushProvider(context.Background(), pushProviderId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test PushProviderApiService ListPushProviders", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.PushProviderApi.ListPushProviders(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test PushProviderApiService ReplacePushProvider", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var pushProviderId string

		resp, httpRes, err := apiClient.PushProviderApi.ReplacePushProvider(context.Background(), pushProviderId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})
}
