/*
Okta Admin Management

Testing ApiTokenApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package okta

import (
	"context"
	"testing"

	openapiclient "./openapi"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_okta_ApiTokenApiService(t *testing.T) {
	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ApiTokenApiService GetApiToken", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var apiTokenId string

		resp, httpRes, err := apiClient.ApiTokenApi.GetApiToken(context.Background(), apiTokenId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test ApiTokenApiService ListApiTokens", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.ApiTokenApi.ListApiTokens(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test ApiTokenApiService RevokeApiToken", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var apiTokenId string

		resp, httpRes, err := apiClient.ApiTokenApi.RevokeApiToken(context.Background(), apiTokenId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test ApiTokenApiService RevokeCurrentApiToken", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.ApiTokenApi.RevokeCurrentApiToken(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})
}
