/*
Okta Admin Management

Testing LinkedObjectApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package okta

import (
	"context"
	"testing"

	openapiclient "./openapi"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_okta_LinkedObjectApiService(t *testing.T) {
	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test LinkedObjectApiService CreateLinkedObjectDefinition", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.LinkedObjectApi.CreateLinkedObjectDefinition(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test LinkedObjectApiService DeleteLinkedObjectDefinition", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var linkedObjectName string

		resp, httpRes, err := apiClient.LinkedObjectApi.DeleteLinkedObjectDefinition(context.Background(), linkedObjectName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test LinkedObjectApiService GetLinkedObjectDefinition", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var linkedObjectName string

		resp, httpRes, err := apiClient.LinkedObjectApi.GetLinkedObjectDefinition(context.Background(), linkedObjectName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test LinkedObjectApiService ListLinkedObjectDefinitions", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.LinkedObjectApi.ListLinkedObjectDefinitions(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})
}
