/*
Okta Admin Management

Testing SessionApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package okta

import (
	"context"
	"testing"

	openapiclient "./openapi"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_okta_SessionApiService(t *testing.T) {
	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SessionApiService CreateSession", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.SessionApi.CreateSession(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test SessionApiService GetSession", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var sessionId string

		resp, httpRes, err := apiClient.SessionApi.GetSession(context.Background(), sessionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test SessionApiService RefreshSession", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var sessionId string

		resp, httpRes, err := apiClient.SessionApi.RefreshSession(context.Background(), sessionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test SessionApiService RevokeSession", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var sessionId string

		resp, httpRes, err := apiClient.SessionApi.RevokeSession(context.Background(), sessionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})
}
