/*
Okta Admin Management

Testing UserTypeApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package okta

import (
	"context"
	"testing"

	openapiclient "./openapi"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_okta_UserTypeApiService(t *testing.T) {
	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test UserTypeApiService CreateUserType", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.UserTypeApi.CreateUserType(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test UserTypeApiService DeleteUserType", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var typeId string

		resp, httpRes, err := apiClient.UserTypeApi.DeleteUserType(context.Background(), typeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test UserTypeApiService GetUserType", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var typeId string

		resp, httpRes, err := apiClient.UserTypeApi.GetUserType(context.Background(), typeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test UserTypeApiService ListUserTypes", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.UserTypeApi.ListUserTypes(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test UserTypeApiService ReplaceUserType", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var typeId string

		resp, httpRes, err := apiClient.UserTypeApi.ReplaceUserType(context.Background(), typeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test UserTypeApiService UpdateUserType", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var typeId string

		resp, httpRes, err := apiClient.UserTypeApi.UpdateUserType(context.Background(), typeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})
}
