/*
Okta Admin Management

Testing HookKeyApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package okta

import (
	"context"
	"testing"

	openapiclient "./openapi"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_okta_HookKeyApiService(t *testing.T) {
	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test HookKeyApiService CreateHookKey", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.HookKeyApi.CreateHookKey(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test HookKeyApiService DeleteHookKey", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var hookKeyId string

		resp, httpRes, err := apiClient.HookKeyApi.DeleteHookKey(context.Background(), hookKeyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test HookKeyApiService GetHookKey", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var hookKeyId string

		resp, httpRes, err := apiClient.HookKeyApi.GetHookKey(context.Background(), hookKeyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test HookKeyApiService GetPublicKey", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var keyId string

		resp, httpRes, err := apiClient.HookKeyApi.GetPublicKey(context.Background(), keyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test HookKeyApiService ListHookKeys", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.HookKeyApi.ListHookKeys(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test HookKeyApiService ReplaceHookKey", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var hookKeyId string

		resp, httpRes, err := apiClient.HookKeyApi.ReplaceHookKey(context.Background(), hookKeyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})
}
