/*
Okta Admin Management

Testing DeviceAssuranceApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package okta

import (
	"context"
	"testing"

	openapiclient "./openapi"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_okta_DeviceAssuranceApiService(t *testing.T) {
	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DeviceAssuranceApiService CreateDeviceAssurancePolicy", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DeviceAssuranceApi.CreateDeviceAssurancePolicy(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test DeviceAssuranceApiService DeleteDeviceAssurancePolicy", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var deviceAssuranceId string

		resp, httpRes, err := apiClient.DeviceAssuranceApi.DeleteDeviceAssurancePolicy(context.Background(), deviceAssuranceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test DeviceAssuranceApiService GetDeviceAssurancePolicy", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var deviceAssuranceId string

		resp, httpRes, err := apiClient.DeviceAssuranceApi.GetDeviceAssurancePolicy(context.Background(), deviceAssuranceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test DeviceAssuranceApiService ListDeviceAssurancePolicies", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DeviceAssuranceApi.ListDeviceAssurancePolicies(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})

	t.Run("Test DeviceAssuranceApiService ReplaceDeviceAssurancePolicy", func(t *testing.T) {
		t.Skip("skip test") // remove to run test

		var deviceAssuranceId string

		resp, httpRes, err := apiClient.DeviceAssuranceApi.ReplaceDeviceAssurancePolicy(context.Background(), deviceAssuranceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
	})
}
